/********************* -*- mode: C; coding: utf-8 -*- *************************/
/**
 * \file     doxygen.h
 *           Additional doxygen sections (no code).
 *
 * \author   Copyright (C) 2006-2020 Ralf Hoppe <ralf.hoppe@dfcgen.de>
 *
 * \page        Configure
 *              See output of \c configure \c --help
 * \page        Make
 * \section     Users
 *              - \c make \c [all] in root directory builds the package
 *              - \c make \c install in root directory installs the package
 *              - \c make \c clean in root directory deletes object files and executable
 * \section     Maintainer
 *              - \c make \c dist in root directory generates a distribution package
 *              - \c make \c dist-debian in root directory builds a Debian package
 *              - \c make \c dist-win32 in root directory builds (on MinGW) a Win32 package
 *              - \c make \c distcheck in root directory checks the package for
 *                distribution (and updates the \e gettext database and \e po files)
 *              - \c make \c maintainer-clean in root directory deletes all object files,
 *                the executable and all distribution files that can be regenerated by
 *                Automake/Autoconf
 *              - \c make \c doxygen in root directory generates the Doxygen
 *                source code documentation
 *              - \c make \c update-po in \e po directory updates the
 *                strings list in file \e de.po
 *              - \c make \c all in \e po directory builds the \e gmo file(s)
 *
 *
 ******************************************************************************/


#ifndef DOXYGEN_H
#define DOXYGEN_H

#endif
