/******************************************************************************/
/**
 * \file
 *           Main dialog management.
 *
 * \author   Copyright (c) Ralf Hoppe
 * \version  $Header: /home/cvs/dfcgen-gtk/include/mainDlg.h,v 1.2 2006-11-04 18:28:27 ralf Exp $
 *
 *
 * \see
 *
 * History:
 * $Log: not supported by cvs2svn $
 * Revision 1.1.1.1  2006/09/11 15:52:21  ralf
 * Initial CVS import
 *
 *
 *
 ******************************************************************************/


#ifndef MAINDLG_H
#define MAINDLG_H


/* INCLUDE FILES **************************************************************/

#include "gui.h"


#ifdef  __cplusplus
extern "C" {
#endif


/* GLOBAL TYPE DECLARATIONS ***************************************************/


/* GLOBAL CONSTANT DECLARATIONS ***********************************************/


/* GLOBAL VARIABLE DECLARATIONS ***********************************************/


/* GLOBAL MACRO DEFINITIONS ***************************************************/


/* EXPORTED FUNCTIONS *********************************************************/


/* FUNCTION *******************************************************************/
/** dfcgen top widget creation.
 *
 *  This function is completely taken over from interface.c, where it has been
 *  generated by glade.
 *
 *
 *  \return     Top widget reference.
 ******************************************************************************/
    GtkWidget* mainDlgCreate (void);


/* FUNCTION *******************************************************************/
/** Updates the project information in statusbar.
 *
 ******************************************************************************/
    void mainDlgUpdatePrjInfo (void);


/* FUNCTION *******************************************************************/
/** Updates the main filter dialog from current project if there is no error
 *  passed in. If there is an critical error (coded as from function filterCheck(),
 *  then it displays an error box. If FLTERR_WARNING (err) indicates loss of
 *  coefficients then a warning will be shown.
 *
 *  \param err      Error indicator with coding as from filterCheck().
 *
 *  \return         Returns TRUE if the error is not FLTERR_CRITICAL(),
 *                  else FALSE.
 ******************************************************************************/
    void mainDlgUpdateAll (const char* filename);



/* FUNCTION *******************************************************************/
/** Updates the filter dialog in main widget from current project.
 *
 ******************************************************************************/
    BOOL mainDlgUpdateFilter (int err);


#ifdef  __cplusplus
}
#endif


#endif /* MAINDLG_H */


/******************************************************************************/
/* END OF FILE                                                                */
/******************************************************************************/

