/******************************************************************************/
/**
 * \file
 *           Main dialog management.
 *
 * \author   Copyright (c) Ralf Hoppe
 * \version  $Header: /home/cvs/dfcgen-gtk/include/mainDlg.h,v 1.1.1.1 2006-09-11 15:52:21 ralf Exp $
 *
 *
 * \see
 *
 * History:
 * $Log: not supported by cvs2svn $
 *
 *
 ******************************************************************************/


#ifndef MAINDLG_H
#define MAINDLG_H


/* INCLUDE FILES **************************************************************/

#include "gui.h"


#ifdef  __cplusplus
extern "C" {
#endif


/* GLOBAL TYPE DECLARATIONS ***************************************************/


/* GLOBAL CONSTANT DECLARATIONS ***********************************************/


/* GLOBAL VARIABLE DECLARATIONS ***********************************************/


/* GLOBAL MACRO DEFINITIONS ***************************************************/


/* EXPORTED FUNCTIONS *********************************************************/

/* FUNCTION *******************************************************************/
/** dfcgen top widget creation.
 *
 *  This function is completely taken over from interface.c, where it has been
 *  generated by glade.
 *
 *
 *  \return     Top widget reference.
 ******************************************************************************/
    GtkWidget* mainDlgCreate (void);


/* FUNCTION *******************************************************************/
/** Updates the filter dialog in main widget from a project (read from file
 *  before).
 *
 *  \param filename     Associated filename in filesystem coding, or NULL to
 *                      reset.
 *
 ******************************************************************************/
    void mainDlgUpdateAll (const char* filename);


/* FUNCTION *******************************************************************/
/** Updates the filter dialog in main widget from current project.
 *
 ******************************************************************************/
    void mainDlgUpdateFilter (void);


#ifdef  __cplusplus
}
#endif


#endif /* MAINDLG_H */


/******************************************************************************/
/* END OF FILE                                                                */
/******************************************************************************/

